apiVersion: v1
kind: Service
metadata:
  name: airflow-service
spec:
  selector:
    app: python
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-service
spec:
  selector:
    app: spark-master
  ports:
    - name: internal
      protocol: TCP
      port: 8090
      targetPort: 8090
    - name: spark
      protocol: TCP
      port: 7077
      targetPort: 7077
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker-service
spec:
  selector:
    app: spark-worker
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8091
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3307
      targetPort: 3306
  type: NodePort
